name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup DBus
      run: mkdir -p /var/run/dbus \ dbus-daemon --config-file=/usr/share/dbus-1/system.conf --print-address
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
